2024-08-16 15:34:56,647 INFO envexp_utils.log Environment created successfully!
2024-08-16 15:34:58,189 INFO envexp_utils.log Testing imports with:
2024-08-16 15:34:58,190 INFO envexp_utils.log 	import sleap
2024-08-16 15:35:47,635 ERROR envexp_utils.log Imports failed!
Traceback (most recent call last):
  File "/Users/liezlmaree/Projects/envexp/envexp/envexp_utils/log.py", line 121, in run_and_log
    raise Exception(error)
Exception: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/liezlmaree/Projects/envexp/envexp/sleap/__init__.py", line 14, in <module>
    import sleap.nn
  File "/Users/liezlmaree/Projects/envexp/envexp/sleap/nn/__init__.py", line 1, in <module>
    import sleap.nn.architectures
  File "/Users/liezlmaree/Projects/envexp/envexp/sleap/nn/architectures/__init__.py", line 4, in <module>
    from sleap.nn.architectures import resnet
  File "/Users/liezlmaree/Projects/envexp/envexp/sleap/nn/architectures/resnet.py", line 56, in <module>
    ) -> Tuple[tf.keras.Model, List[IntermediateFeature]]:
AttributeError: module 'keras.api._v2.keras' has no attribute 'Model'

